name: Build CS2-Local-GC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Create release directory
        run: mkdir ${{ github.workspace }}\release

      - name: Setup vcpkg
        shell: cmd
        run: |
          git clone https://github.com/Microsoft/vcpkg.git %CD%\vcpkg
          %CD%\vcpkg\bootstrap-vcpkg.bat
          %CD%\vcpkg\vcpkg install --triplet x64-windows

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -A x64 -T v142 ^
            -B ${{ github.workspace }}\build ^
            -S ${{ github.workspace }} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DVCPKG_TARGET_TRIPLET=x64-windows ^
            -DOUTDIR=${{ github.workspace }}\release

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}\build --config Release --target Injector GC_Core

      - name: Package files
        shell: bash
        run: |
          cp README.md release/
          mkdir -p release/licenses
          cp LICENSE release/licenses/LICENSE-cs2-local-gc.txt
          cp build/_deps/protobuf-src/LICENSE release/licenses/LICENSE-protobuf.txt
          cp build/_deps/nlohmann_json-src/LICENSE.MIT release/licenses/LICENSE-json.txt
          cp config.json release/
          cp resources/schema_2026.json release/
          mkdir -p release/cs2_gc
          cp examples/config.txt release/cs2_gc/
          cp examples/inventory.txt release/cs2_gc/

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "$env:GITHUB_WORKSPACE\release\*" `
            -DestinationPath "$env:GITHUB_WORKSPACE\cs2-local-gc-windows.zip" `
            -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs2-local-gc-windows
          path: ${{ github.workspace }}\cs2-local-gc-windows.zip

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Continuous Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          TAG=continuous
          FILE=$(find artifacts -name "*.zip")

          if [ -n "$FILE" ]; then
            gh release delete "$TAG" --cleanup-tag --repo "$REPO" --yes || true
            sleep 10

            gh release create "$TAG" \
              --repo "$REPO" \
              --title "Continuous Build" \
              --notes ""



            gh release upload "$TAG" "$FILE" --repo "$REPO" --clobber
          fi
