name: Build CS2-Local-GC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Create release directory
        run: mkdir ${{ github.workspace }}\release

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -A x64 ^
            -B ${{ github.workspace }}\build ^
            -S ${{ github.workspace }} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DOUTDIR=${{ github.workspace }}\release

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}\build --config Release

      - name: Copy files
        shell: cmd
        run: |
          copy build\src\gc\Release\GC_Core.dll release\
          copy config.json release\
          copy resources\schema_2026.json release\

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "$env:GITHUB_WORKSPACE\release\*" `
            -DestinationPath "$env:GITHUB_WORKSPACE\cs2_gc.zip" `
            -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs2_gc
          path: ${{ github.workspace }}\cs2_gc.zip

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Continuous Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          TAG=continuous
          FILE=$(find artifacts -name "*.zip")

          if [ -n "$FILE" ]; then
            gh release delete "$TAG" --cleanup-tag --repo "$REPO" --yes || true
            sleep 5

            gh release create "$TAG" \
              --repo "$REPO" \
              --title "Continuous Build" \
              --notes "" \
              --target "$SHA"

            gh release upload "$TAG" "$FILE" --repo "$REPO" --clobber
          fi
